"""Konstanten und Entitaets-Beschreibungen fuer die Wattpilot-Integration.

Diese Datei wurde aus der API-Definition der Bibliothek wattpilot-api
erzeugt (wattpilot_api/resources/wattpilot.yaml, Version 1.4.0).

Die Anzeigenamen stehen nicht hier, sondern in den Sprachdateien unter
translations/. Jede Entitaet verweist ueber translation_key darauf.

Jeder Eintrag beschreibt genau eine Property des Wattpilot:
  key              Property-Schluessel im Wattpilot-Protokoll
  translation_key  Verweis auf den Namen in den Sprachdateien
  unit             Masseinheit oder None
  device_class     Home-Assistant-Geraeteklasse oder None
  value_map        Zuordnung Zahlenwert -> Zustandsschluessel oder None
  enabled          ob die Entitaet standardmaessig aktiv ist
  category         None, "config" oder "diagnostic"
  range            (min, max, schrittweite) fuer Number-Entitaeten
"""

from __future__ import annotations

from dataclasses import dataclass

DOMAIN = "fronius_wattpilot_lutarym"

CONF_HOST = "host"
CONF_PASSWORD = "password"

DEFAULT_NAME = "Fronius Wattpilot"

# Unterstuetzte Sprachen der Integration
SUPPORTED_LANGUAGES = ("de", "en", "fr")

# Dienst zum Setzen beliebiger Properties
SERVICE_SET_PROPERTY = "set_property"
ATTR_PROPERTY = "property"
ATTR_VALUE = "value"

# Property, die einen Neustart des Geraets ausloest
PROP_REBOOT = "rst"

# Property mit der Liste der registrierten RFID-Karten
PROP_CARDS = "cards"

# Hoechstzahl an RFID-Karten, fuer die Entitaeten angelegt werden
MAX_RFID_CARDS = 10

# Einstellung: nur Entitaeten anlegen, die das Geraet auch liefert
OPT_ONLY_AVAILABLE = "only_available"
DEFAULT_ONLY_AVAILABLE = True


@dataclass(frozen=True)
class WattpilotDescription:
    """Beschreibung einer einzelnen Wattpilot-Property."""

    key: str
    translation_key: str
    unit: str | None = None
    device_class: str | None = None
    value_map: dict[str, str] | None = None
    enabled: bool = False
    category: str | None = None
    range: tuple[float, float, float] | None = None
    state_class: str | None = None



SENSORS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="acu",
        translation_key="acu",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="al1",
        translation_key="al1",
        unit="A",
        device_class="current",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="al2",
        translation_key="al2",
        unit="A",
        device_class="current",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="al3",
        translation_key="al3",
        unit="A",
        device_class="current",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="al4",
        translation_key="al4",
        unit="A",
        device_class="current",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="al5",
        translation_key="al5",
        unit="A",
        device_class="current",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="amt",
        translation_key="amt",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="apd",
        translation_key="apd",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_idf_ver",
        translation_key="apd_idf_ver",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_project_name",
        translation_key="apd_project_name",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_secure_version",
        translation_key="apd_secure_version",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_sha256",
        translation_key="apd_sha256",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_timestamp",
        translation_key="apd_timestamp",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="apd_version",
        translation_key="apd_version",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="arv",
        translation_key="arv",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="awcp",
        translation_key="awcp",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="awcp_end",
        translation_key="awcp_end",
        enabled=True,
    ),
    WattpilotDescription(
        key="awcp_marketprice",
        translation_key="awcp_marketprice",
        enabled=True,
    ),
    WattpilotDescription(
        key="awcp_start",
        translation_key="awcp_start",
        enabled=True,
    ),
    WattpilotDescription(
        key="awpl",
        translation_key="awpl",
        enabled=True,
    ),
    WattpilotDescription(
        key="car",
        translation_key="car",
        value_map={"0": "unknown_error", "1": "idle", "2": "charging", "3": "waitcar", "4": "complete", "5": "error"},
        enabled=True,
    ),
    WattpilotDescription(
        key="cards",
        translation_key="cards",
        enabled=True,
    ),
    WattpilotDescription(
        key="cbl",
        translation_key="cbl",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="ccrv",
        translation_key="ccrv",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ccu",
        translation_key="ccu",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ccw",
        translation_key="ccw",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cdi",
        translation_key="cdi",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cdi_type",
        translation_key="cdi_type",
        value_map={"0": "counter", "1": "duration"},
        enabled=True,
    ),
    WattpilotDescription(
        key="cdi_value",
        translation_key="cdi_value",
        enabled=True,
    ),
    WattpilotDescription(
        key="clp",
        translation_key="clp",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cus",
        translation_key="cus",
        value_map={"0": "unknown", "1": "unlocked", "2": "unlockfailed", "3": "locked", "4": "lockfailed", "5": "lockunlockpowerout"},
        enabled=True,
    ),
    WattpilotDescription(
        key="cwsca",
        translation_key="cwsca",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="deltaa",
        translation_key="deltaa",
        enabled=True,
    ),
    WattpilotDescription(
        key="deltap",
        translation_key="deltap",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="dns",
        translation_key="dns",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ecf",
        translation_key="ecf",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ecf_div",
        translation_key="ecf_div",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ecf_freq_mhz",
        translation_key="ecf_freq_mhz",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ecf_source",
        translation_key="ecf_source",
        value_map={"0": "xtal", "1": "pll", "2": "v8m", "3": "apll"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ecf_source_freq_mhz",
        translation_key="ecf_source_freq_mhz",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eci",
        translation_key="eci",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eci_cores",
        translation_key="eci_cores",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eci_features",
        translation_key="eci_features",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eci_model",
        translation_key="eci_model",
        value_map={"1": "esp32", "2": "esp32s2", "4": "esp32s3", "5": "esp32c3"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eci_revision",
        translation_key="eci_revision",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="efh",
        translation_key="efh",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="efh32",
        translation_key="efh32",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="efh8",
        translation_key="efh8",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="efi",
        translation_key="efi",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="efi_spi_mode",
        translation_key="efi_spi_mode",
        value_map={"0": "qio", "1": "qout", "2": "dio", "3": "dout", "4": "fast_read", "5": "slow_read"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="efi_spi_size",
        translation_key="efi_spi_size",
        value_map={"0": "v1mb", "1": "v2mb", "2": "v4mb", "3": "v8mb", "4": "v16mb", "5": "max"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="efi_spi_speed",
        translation_key="efi_spi_speed",
        value_map={"0": "v40m", "1": "v26m", "2": "v20m", "15": "v80m"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ehs",
        translation_key="ehs",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="emfh",
        translation_key="emfh",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="emhb",
        translation_key="emhb",
        unit="B",
        device_class="data_size",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="err",
        translation_key="err",
        value_map={"0": "none", "1": "fiac", "2": "fidc", "3": "phase", "4": "overvolt", "5": "overamp", "6": "diode", "7": "ppinvalid", "8": "gndinvalid", "9": "contactorstuck", "10": "contactormiss", "11": "fiunknown", "12": "unknown", "13": "overtemp", "14": "nocomm", "15": "statuslockstuckopen", "16": "statuslockstucklocked", "20": "reserved20", "21": "reserved21", "22": "reserved22", "23": "reserved23", "24": "reserved24"},
        enabled=True,
    ),
    WattpilotDescription(
        key="esr",
        translation_key="esr",
        value_map={"0": "no_mean", "1": "poweron_reset", "3": "sw_reset", "4": "owdt_reset", "5": "deepsleep_reset", "6": "sdio_reset", "7": "tg0wdt_sys_reset", "8": "tg1wdt_sys_reset", "9": "rtcwdt_sys_reset", "10": "intrusion_reset", "11": "tgwdt_cpu_reset", "12": "sw_cpu_reset", "13": "rtcwdt_cpu_reset", "14": "ext_cpu_reset", "15": "rtcwdt_brown_out_reset", "16": "rtcwdt_rtc_reset"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="eto",
        translation_key="eto",
        unit="Wh",
        device_class="energy",
        enabled=True,
        state_class="total_increasing",
    ),
    WattpilotDescription(
        key="etop",
        translation_key="etop",
        unit="Wh",
        device_class="energy",
        enabled=True,
        state_class="total_increasing",
    ),
    WattpilotDescription(
        key="fam",
        translation_key="fam",
        enabled=True,
        range=(0, 100, 1),
    ),
    WattpilotDescription(
        key="fbuf_age",
        translation_key="fbuf_age",
        enabled=True,
    ),
    WattpilotDescription(
        key="fbuf_akkuMode",
        translation_key="fbuf_akkumode",
        enabled=True,
    ),
    WattpilotDescription(
        key="fbuf_akkuSOC",
        translation_key="fbuf_akkusoc",
        unit="%",
        enabled=True,
    ),
    WattpilotDescription(
        key="fbuf_ohmpilotState",
        translation_key="fbuf_ohmpilotstate",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fbuf_ohmpilotTemperature",
        translation_key="fbuf_ohmpilottemperature",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fbuf_pAcTotal",
        translation_key="fbuf_pactotal",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="fbuf_pAkku",
        translation_key="fbuf_pakku",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="fbuf_pGrid",
        translation_key="fbuf_pgrid",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="fbuf_pPv",
        translation_key="fbuf_ppv",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="fem",
        translation_key="fem",
        value_map={"0": "disabled", "1": "development", "2": "release"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ferm",
        translation_key="ferm",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ffb",
        translation_key="ffb",
        value_map={"0": "noproblem", "1": "problemlock", "2": "problemunlock"},
        enabled=True,
    ),
    WattpilotDescription(
        key="ffba",
        translation_key="ffba",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ffna",
        translation_key="ffna",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fhz",
        translation_key="fhz",
        unit="Hz",
        device_class="frequency",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="fot",
        translation_key="fot",
        unit="°C",
        device_class="temperature",
        category="config",
        range=(0, 100, 1),
        state_class="measurement",
    ),
    WattpilotDescription(
        key="frm",
        translation_key="frm",
        value_map={"0": "preferpowerfromgrid", "1": "default", "2": "preferpowertogrid"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fsptws",
        translation_key="fsptws",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fwan",
        translation_key="fwan",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fwc",
        translation_key="fwc",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="fwv",
        translation_key="fwv",
        enabled=True,
    ),
    WattpilotDescription(
        key="host",
        translation_key="host",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ido",
        translation_key="ido",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="inva",
        translation_key="inva",
        unit="ms",
        enabled=True,
    ),
    WattpilotDescription(
        key="lbp",
        translation_key="lbp",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lccfc",
        translation_key="lccfc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lccfi",
        translation_key="lccfi",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lcctc",
        translation_key="lcctc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lck",
        translation_key="lck",
        value_map={"0": "normal", "1": "autounlock", "2": "alwayslock", "3": "forceunlock"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="led",
        translation_key="led",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lfspt",
        translation_key="lfspt",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lmsc",
        translation_key="lmsc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="loa",
        translation_key="loa",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="loc",
        translation_key="loc",
        enabled=True,
    ),
    WattpilotDescription(
        key="lom",
        translation_key="lom",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="los",
        translation_key="los",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lpsc",
        translation_key="lpsc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lssfc",
        translation_key="lssfc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="lsstc",
        translation_key="lsstc",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="map",
        translation_key="map",
        enabled=True,
    ),
    WattpilotDescription(
        key="mcpea",
        translation_key="mcpea",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="mod",
        translation_key="mod",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="modelStatus",
        translation_key="modelstatus",
        value_map={"0": "notchargingbecausenochargectrldata", "1": "notchargingbecauseovertemperature", "2": "notchargingbecauseaccesscontrolwait", "3": "chargingbecauseforcestateon", "4": "notchargingbecauseforcestateoff", "5": "notchargingbecausescheduler", "6": "notchargingbecauseenergylimit", "7": "chargingbecauseawattarpricelow", "8": "chargingbecauseautomaticstoptestladung", "9": "chargingbecauseautomaticstopnotenoughtime", "10": "chargingbecauseautomaticstop", "11": "chargingbecauseautomaticstopnoclock", "12": "chargingbecausepvsurplus", "13": "chargingbecausefallbackgoedefault", "14": "chargingbecausefallbackgoescheduler", "15": "chargingbecausefallbackdefault", "16": "notchargingbecausefallbackgoeawattar", "17": "notchargingbecausefallbackawattar", "18": "notchargingbecausefallbackautomaticstop", "19": "chargingbecausecarcompatibilitykeepalive", "20": "chargingbecausechargepausenotallowed", "22": "notchargingbecausesimulateunplugging", "23": "notchargingbecausephaseswitch", "24": "notchargingbecauseminpauseduration"},
        enabled=True,
    ),
    WattpilotDescription(
        key="msi",
        translation_key="msi",
        value_map={"0": "notchargingbecausenochargectrldata", "1": "notchargingbecauseovertemperature", "2": "notchargingbecauseaccesscontrolwait", "3": "chargingbecauseforcestateon", "4": "notchargingbecauseforcestateoff", "5": "notchargingbecausescheduler", "6": "notchargingbecauseenergylimit", "7": "chargingbecauseawattarpricelow", "8": "chargingbecauseautomaticstoptestladung", "9": "chargingbecauseautomaticstopnotenoughtime", "10": "chargingbecauseautomaticstop", "11": "chargingbecauseautomaticstopnoclock", "12": "chargingbecausepvsurplus", "13": "chargingbecausefallbackgoedefault", "14": "chargingbecausefallbackgoescheduler", "15": "chargingbecausefallbackdefault", "16": "notchargingbecausefallbackgoeawattar", "17": "notchargingbecausefallbackawattar", "18": "notchargingbecausefallbackautomaticstop", "19": "chargingbecausecarcompatibilitykeepalive", "20": "chargingbecausechargepausenotallowed", "22": "notchargingbecausesimulateunplugging", "23": "notchargingbecausephaseswitch", "24": "notchargingbecauseminpauseduration"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="nif",
        translation_key="nif",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="nrg",
        translation_key="nrg",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="nrg_il1",
        translation_key="nrg_il1",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_il2",
        translation_key="nrg_il2",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_il3",
        translation_key="nrg_il3",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_pfl1",
        translation_key="nrg_pfl1",
        unit="%",
        enabled=True,
    ),
    WattpilotDescription(
        key="nrg_pfl2",
        translation_key="nrg_pfl2",
        unit="%",
        enabled=True,
    ),
    WattpilotDescription(
        key="nrg_pfl3",
        translation_key="nrg_pfl3",
        unit="%",
        enabled=True,
    ),
    WattpilotDescription(
        key="nrg_pfn",
        translation_key="nrg_pfn",
        unit="%",
        enabled=True,
    ),
    WattpilotDescription(
        key="nrg_pl1",
        translation_key="nrg_pl1",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_pl2",
        translation_key="nrg_pl2",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_pl3",
        translation_key="nrg_pl3",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_pn",
        translation_key="nrg_pn",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_ptotal",
        translation_key="nrg_ptotal",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_ul1",
        translation_key="nrg_ul1",
        unit="V",
        device_class="voltage",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_ul2",
        translation_key="nrg_ul2",
        unit="V",
        device_class="voltage",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_ul3",
        translation_key="nrg_ul3",
        unit="V",
        device_class="voltage",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="nrg_un",
        translation_key="nrg_un",
        unit="V",
        device_class="voltage",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="oca",
        translation_key="oca",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ocl",
        translation_key="ocl",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ocm",
        translation_key="ocm",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ocp",
        translation_key="ocp",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ocs",
        translation_key="ocs",
        value_map={"0": "idle", "1": "updating", "2": "failed", "3": "succeeded"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ocu",
        translation_key="ocu",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="oem",
        translation_key="oem",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="onv",
        translation_key="onv",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="otap",
        translation_key="otap",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pakku",
        translation_key="pakku",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="part",
        translation_key="part",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pgrid",
        translation_key="pgrid",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pha",
        translation_key="pha",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pnp",
        translation_key="pnp",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ppv",
        translation_key="ppv",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pto",
        translation_key="pto",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pvopt_averagePAkku",
        translation_key="pvopt_averagepakku",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_averagePGrid",
        translation_key="pvopt_averagepgrid",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_averagePOhmpilot",
        translation_key="pvopt_averagepohmpilot",
        unit="W",
        device_class="power",
        category="diagnostic",
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_averagePPv",
        translation_key="pvopt_averageppv",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_deltaA",
        translation_key="pvopt_deltaa",
        unit="A",
        device_class="current",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_deltaP",
        translation_key="pvopt_deltap",
        unit="W",
        device_class="power",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="pvopt_specialCase",
        translation_key="pvopt_specialcase",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="pwm",
        translation_key="pwm",
        value_map={"0": "force_3", "1": "wish_1", "2": "wish_3"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="qsc",
        translation_key="qsc",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="qsw",
        translation_key="qsw",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rbc",
        translation_key="rbc",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rbt",
        translation_key="rbt",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rcd",
        translation_key="rcd",
        unit="us",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rfb",
        translation_key="rfb",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rr",
        translation_key="rr",
        value_map={"0": "unknown", "1": "poweron", "2": "ext", "3": "sw", "4": "panic", "5": "int_wdt", "6": "task_wdt", "7": "wdt", "8": "deepsleep", "9": "brownout", "10": "sdio"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="rssi",
        translation_key="rssi",
        unit="dBm",
        device_class="signal_strength",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="scaa",
        translation_key="scaa",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="scan",
        translation_key="scan",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="scas",
        translation_key="scas",
        value_map={"0": "none", "1": "scanning", "2": "finished", "3": "failed"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="sch_satur",
        translation_key="sch_satur",
        enabled=True,
    ),
    WattpilotDescription(
        key="sch_satur_control",
        translation_key="sch_satur_control",
        value_map={"0": "disabled", "1": "inside", "2": "outside"},
        enabled=True,
    ),
    WattpilotDescription(
        key="sch_sund",
        translation_key="sch_sund",
        enabled=True,
    ),
    WattpilotDescription(
        key="sch_sund_control",
        translation_key="sch_sund_control",
        value_map={"0": "disabled", "1": "inside", "2": "outside"},
        enabled=True,
    ),
    WattpilotDescription(
        key="sch_week",
        translation_key="sch_week",
        enabled=True,
    ),
    WattpilotDescription(
        key="sch_week_control",
        translation_key="sch_week_control",
        value_map={"0": "disabled", "1": "inside", "2": "outside"},
        enabled=True,
    ),
    WattpilotDescription(
        key="sse",
        translation_key="sse",
        enabled=True,
    ),
    WattpilotDescription(
        key="tma",
        translation_key="tma",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="tma_1",
        translation_key="tma_1",
        unit="°C",
        device_class="temperature",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="tma_2",
        translation_key="tma_2",
        unit="°C",
        device_class="temperature",
        enabled=True,
        state_class="measurement",
    ),
    WattpilotDescription(
        key="tpa",
        translation_key="tpa",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ts",
        translation_key="ts",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="tsom",
        translation_key="tsom",
        value_map={"0": "poll", "1": "listenonly"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="tssi",
        translation_key="tssi",
        unit="ms",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="tssm",
        translation_key="tssm",
        value_map={"0": "immed", "1": "smooth"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="tsss",
        translation_key="tsss",
        value_map={"0": "reset", "1": "completed", "2": "in_progress"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="typ",
        translation_key="typ",
        enabled=True,
    ),
    WattpilotDescription(
        key="var",
        translation_key="var",
        value_map={"11": "v11kw_16a", "22": "v22kw_32a"},
        enabled=True,
    ),
    WattpilotDescription(
        key="wcb",
        translation_key="wcb",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wcch",
        translation_key="wcch",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wccw",
        translation_key="wccw",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wfb",
        translation_key="wfb",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wh",
        translation_key="wh",
        unit="Wh",
        device_class="energy",
        enabled=True,
        state_class="total_increasing",
    ),
    WattpilotDescription(
        key="wpb",
        translation_key="wpb",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wsc",
        translation_key="wsc",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wsm",
        translation_key="wsm",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wsms",
        translation_key="wsms",
        value_map={"0": "none", "1": "scanning", "2": "connecting", "3": "connected"},
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wss",
        translation_key="wss",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="wst",
        translation_key="wst",
        value_map={"0": "idle_status", "1": "no_ssid_avail", "2": "scan_completed", "3": "connected", "4": "connect_failed", "5": "connection_lost", "6": "disconnected", "8": "connecting", "9": "disconnecting", "10": "no_shield"},
        category="diagnostic",
    ),
)


BINARY_SENSORS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="adi",
        translation_key="adi",
        enabled=True,
    ),
    WattpilotDescription(
        key="alw",
        translation_key="alw",
        enabled=True,
    ),
    WattpilotDescription(
        key="cca",
        translation_key="cca",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cpe",
        translation_key="cpe",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cpr",
        translation_key="cpr",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cws",
        translation_key="cws",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="cwsc",
        translation_key="cwsc",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="ful",
        translation_key="ful",
        enabled=True,
    ),
    WattpilotDescription(
        key="ocuca",
        translation_key="ocuca",
        category="diagnostic",
    ),
    WattpilotDescription(
        key="sbe",
        translation_key="sbe",
        category="diagnostic",
    ),
)


NUMBERS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="ama",
        translation_key="ama",
        unit="A",
        device_class="current",
        enabled=True,
        range=(6, 32, 1),
    ),
    WattpilotDescription(
        key="amp",
        translation_key="amp",
        unit="A",
        device_class="current",
        enabled=True,
        range=(6, 32, 1),
    ),
    WattpilotDescription(
        key="awp",
        translation_key="awp",
        enabled=True,
        range=(-100, 100, 0.1),
    ),
    WattpilotDescription(
        key="cco",
        translation_key="cco",
        enabled=True,
        category="config",
        range=(0, 100, 0.1),
    ),
    WattpilotDescription(
        key="dwo",
        translation_key="dwo",
        unit="Wh",
        device_class="energy",
        enabled=True,
        range=(0, 100000, 100),
    ),
    WattpilotDescription(
        key="fmt",
        translation_key="fmt",
        unit="ms",
        enabled=True,
        range=(0, 7200000, 60000),
    ),
    WattpilotDescription(
        key="fst",
        translation_key="fst",
        unit="W",
        device_class="power",
        enabled=True,
        range=(-10000, 10000, 100),
    ),
    WattpilotDescription(
        key="lbr",
        translation_key="lbr",
        enabled=True,
        category="config",
        range=(0, 255, 1),
    ),
    WattpilotDescription(
        key="lof",
        translation_key="lof",
        unit="A",
        device_class="current",
        enabled=True,
        range=(0, 32, 1),
    ),
    WattpilotDescription(
        key="lop",
        translation_key="lop",
        enabled=True,
        category="config",
        range=(0, 100, 1),
    ),
    WattpilotDescription(
        key="lot",
        translation_key="lot",
        unit="A",
        device_class="current",
        enabled=True,
        range=(6, 200, 1),
    ),
    WattpilotDescription(
        key="mca",
        translation_key="mca",
        unit="A",
        device_class="current",
        enabled=True,
        range=(6, 32, 1),
    ),
    WattpilotDescription(
        key="mci",
        translation_key="mci",
        unit="ms",
        enabled=True,
        range=(0, 3600000, 60000),
    ),
    WattpilotDescription(
        key="mcpd",
        translation_key="mcpd",
        unit="ms",
        category="config",
        range=(0, 3600000, 60000),
    ),
    WattpilotDescription(
        key="mptwt",
        translation_key="mptwt",
        unit="ms",
        category="config",
        range=(0, 600000, 10000),
    ),
    WattpilotDescription(
        key="mpwst",
        translation_key="mpwst",
        unit="ms",
        category="config",
        range=(0, 600000, 10000),
    ),
    WattpilotDescription(
        key="po",
        translation_key="po",
        unit="W",
        device_class="power",
        enabled=True,
        range=(-5000, 5000, 50),
    ),
    WattpilotDescription(
        key="psh",
        translation_key="psh",
        unit="W",
        device_class="power",
        enabled=True,
        range=(0, 5000, 50),
    ),
    WattpilotDescription(
        key="psmd",
        translation_key="psmd",
        unit="ms",
        category="config",
        range=(0, 3600000, 60000),
    ),
    WattpilotDescription(
        key="sh",
        translation_key="sh",
        unit="W",
        device_class="power",
        enabled=True,
        range=(0, 5000, 50),
    ),
    WattpilotDescription(
        key="spl3",
        translation_key="spl3",
        unit="W",
        device_class="power",
        enabled=True,
        range=(0, 20000, 100),
    ),
    WattpilotDescription(
        key="sumd",
        translation_key="sumd",
        unit="ms",
        category="config",
        range=(0, 600000, 10000),
    ),
    WattpilotDescription(
        key="tof",
        translation_key="tof",
        unit="min",
        category="config",
        range=(-720, 840, 15),
    ),
    WattpilotDescription(
        key="trx",
        translation_key="trx",
        enabled=True,
        range=(0, 10, 1),
    ),
    WattpilotDescription(
        key="zfo",
        translation_key="zfo",
        unit="W",
        device_class="power",
        enabled=True,
        range=(-5000, 5000, 50),
    ),
)


SELECTS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="acs",
        translation_key="acs",
        value_map={"0": "open", "1": "wait"},
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="awc",
        translation_key="awc",
        value_map={"0": "austria", "1": "germany"},
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="frc",
        translation_key="frc",
        value_map={"0": "neutral", "1": "off", "2": "on"},
        enabled=True,
    ),
    WattpilotDescription(
        key="lmo",
        translation_key="lmo",
        value_map={"3": "default", "4": "awattar", "5": "automaticstop"},
        enabled=True,
    ),
    WattpilotDescription(
        key="loty",
        translation_key="loty",
        value_map={"0": "static", "1": "dynamic"},
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="psm",
        translation_key="psm",
        value_map={"0": "auto", "1": "force_1", "2": "force_3"},
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="tds",
        translation_key="tds",
        value_map={"0": "none", "1": "europeansummertime", "2": "usdaylighttime"},
        category="config",
    ),
    WattpilotDescription(
        key="ust",
        translation_key="ust",
        value_map={"0": "normal", "1": "autounlock", "2": "alwayslock"},
        enabled=True,
        category="config",
    ),
)


SWITCHS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="bac",
        translation_key="bac",
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="cwe",
        translation_key="cwe",
        category="config",
    ),
    WattpilotDescription(
        key="esk",
        translation_key="esk",
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="fsp",
        translation_key="fsp",
        enabled=True,
    ),
    WattpilotDescription(
        key="fup",
        translation_key="fup",
        enabled=True,
    ),
    WattpilotDescription(
        key="fzf",
        translation_key="fzf",
        enabled=True,
    ),
    WattpilotDescription(
        key="hsa",
        translation_key="hsa",
        category="config",
    ),
    WattpilotDescription(
        key="hws",
        translation_key="hws",
        category="config",
    ),
    WattpilotDescription(
        key="loe",
        translation_key="loe",
        enabled=True,
    ),
    WattpilotDescription(
        key="lse",
        translation_key="lse",
        category="config",
    ),
    WattpilotDescription(
        key="nmo",
        translation_key="nmo",
        category="config",
    ),
    WattpilotDescription(
        key="su",
        translation_key="su",
        category="config",
    ),
    WattpilotDescription(
        key="sua",
        translation_key="sua",
        category="config",
    ),
    WattpilotDescription(
        key="tse",
        translation_key="tse",
        category="config",
    ),
    WattpilotDescription(
        key="upo",
        translation_key="upo",
        category="config",
    ),
    WattpilotDescription(
        key="wen",
        translation_key="wen",
        category="config",
    ),
)


TEXTS: tuple[WattpilotDescription, ...] = (
    WattpilotDescription(
        key="cch",
        translation_key="cch",
        category="config",
    ),
    WattpilotDescription(
        key="cfi",
        translation_key="cfi",
        category="config",
    ),
    WattpilotDescription(
        key="cid",
        translation_key="cid",
        category="config",
    ),
    WattpilotDescription(
        key="ct",
        translation_key="ct",
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="cwc",
        translation_key="cwc",
        category="config",
    ),
    WattpilotDescription(
        key="fna",
        translation_key="fna",
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="log",
        translation_key="log",
        enabled=True,
        category="config",
    ),
    WattpilotDescription(
        key="utc",
        translation_key="utc",
        enabled=True,
    ),
    WattpilotDescription(
        key="wan",
        translation_key="wan",
        category="config",
    ),
)

